baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "UDPA学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
# General information
    author = "敖小剑"
    keywords = "UDPA,学习笔记,敖小剑"
    description = "UDPA学习笔记。"
    copyright = "版权所有，转载请注明出处"
    
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/skyao/learning-udpa"
    
    version = ""
    logo = "images/logo.png"
    favicon = ""
    
    permalink = "#"
    
    # reward button, comment this to disable it
    reward = true
    
    # Custom assets
    custom_css = []
    custom_js  = []
    
    # Syntax highlighting theme
    highlight_css  = ""
    
    [params.palette]
    	primary = "red"
    	accent  = "teal"
    
    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "API"
	identifier = "api"
	url    = "/api/"
	weight = 300

[[menu.main]]
	name   = "Type"
	identifier = "api-type"
	url    = "/api/type/"
	weight = 310
	parent = "api"

[[menu.main]]
	name   = "Service"
	identifier = "api-service"
	url    = "/api/service/"
	weight = 320
	parent = "api"

[[menu.main]]
	name   = "Data"
	identifier = "api-data"
	url    = "/api/data/"
	weight = 330
	parent = "api"

[[menu.main]]
	name   = "Annotations"
	identifier = "api-annotations"
	url    = "/api/annotations/"
	weight = 340
	parent = "api"

[[menu.main]]
	name   = "设计"
	identifier = "design"
	url    = "/design/"
	weight = 500

[[menu.main]]
	name   = "Transport"
	identifier = "design-transport"
	url    = "/design/transport/"
	weight = 510
	parent = "design"

[[menu.main]]
	name   = "Data Model"
	identifier = "design-datamodel"
	url    = "/design/datamodel/"
	weight = 520
	parent = "design"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


